### ISSUE TITLE
Discord info is invalid

### ISSUE THREAD

**Issue by Kenny2github** [12944qwerty/12944qwerty.github.io#2]
(I open this issue here because it's the one place that it's fitting to talk about it.)

Your Discord info, as shown on the website, is invalid. If I try to send a friend request to `12944qwerty#9317`, I get a "Hm, didn't work" response.

This has two possible causes:
- You've misspelled your Discord info
- You have your friend request settings set against "everyone". Make sure your settings are as follows in the "Privacy & Safety" section (or at the very least, the "everyone" option is turned on):
![image](https://user-images.githubusercontent.com/28599280/53282215-a0316500-376f-11e9-935f-22b695e1deb3.png)
If you have your settings set against "everyone" deliberately, then I recommend you remove your Discord info from your site, as it's not going to help anyone. If that is the case, you can add me as a friend instead of the other way around: `kenny2discord#1024`

**Comment by 12944qwerty** [comment]
I tried adding you but it didn't work. It said didn't work. Also, just
realized. It is 12944qwert#9317. Also, my friend settings are all enabled.

**Comment by Kenny2github** [comment]
I've sent you a friend request. It's strange that you couldn't add me, though... I definitely spelled my info right and I have all three settings on.

**Comment by 12944qwerty** [comment]
hmm.... Anyway, I talked with banana and he invited me to the wiki server.

**Comment by 12944qwerty** [comment]
What? I also realized why I wasn't able to friend you. I kept doing kenny2discord#5021

**Comment by Kenny2github** [comment]
That was my old info, before I got Nitro ;P

**Comment by 12944qwerty** [comment]
do you buy nitro?

**Comment by Kenny2github** [comment]
Yes, though jakel181 gifted it to me for the first month.
