### ISSUE TITLE
Can the background color of the site be changed?

### ISSUE THREAD

**Issue by abhishekshahane** [12944qwerty/12944qwerty.github.io#4]
Can the background color of the site be changed from gray, to a color that goes with red?

**Comment by 12944qwerty** [comment]
I thought that gray was perfect with red?


Besides, this site is old and I haven't updated in a really long time

**Comment by abhishekshahane** [comment]
Nah, it kinda doesn't in this case.
Anyways, yeah the site is really old so whatever
